### ISSUE TITLE
создать сервер

### ISSUE THREAD

**Issue by RUCItLrHy3Ub** [gdps-xyz/future#6]
ps!c

**Comment by Nasos3** [comment]
с добрэм утром

**Comment by Nasos3** [comment]
<:cat_frozen:917874923869990952>

**Comment by Nasos3** [comment]
пухахахаха потомки юзают мой прикол 😈😈😈

**Comment by Nasos3** [comment]
СЛАВА НВОРДАМ

**Comment by Nasos3** [comment]
СЛАВА НВОРДАМ

**Comment by Nasos3** [comment]
СЛАВА НВОРДАМ

**Comment by DiegoArmando-27** [comment]
ауеее

**Comment by Nasos3** [comment]
да не пингаются они гений

**Comment by AleonDM** [comment]
как сделать геометрия деш пишет недостаточно прав

**Comment by DiegoArmando-27** [comment]
ууу оффтоп

**Comment by Nasos3** [comment]
<:meme_Prikolno:843056672564838450>

**Comment by Nasos3** [comment]
ФРИХОСТИНГ ЗАКРЫВАЕТСЯ ЗАВТРА🚨🚨 БАНГА САМ ТАК ВЧЕРА СКАЗАЛА

**Comment by Nasos3** [comment]
СКАЗАЛ

**Comment by Nasos3** [comment]
а если я нворд скажу

**Comment by DiegoArmando-27** [comment]
> а если я нворд скажу
[p

**Comment by Partur-dev** [comment]
> а если я нворд скажу

я тебя уебу и тут и на фх

**Comment by cafeed28** [comment]
> > а если я нворд скажу
> 
> я тебя уебу и тут и на фх

а схуяли если это не относится к фх иди нахуй

**Comment by cafeed28** [comment]
это не чат фх это гитхаб

**Comment by cafeed28** [comment]
и похуй что логгер на фх настроен иди нахуй

**Comment by Partur-dev** [comment]
> > > а если я нворд скажу
> > 
> > 
> > я тебя уебу и тут и на фх
> 
> а схуяли если это не относится к фх иди нахуй

матиеу так сказал

**Comment by cafeed28** [comment]
> > > > а если я нворд скажу
> > > 
> > > 
> > > я тебя уебу и тут и на фх
> > 
> > а схуяли если это не относится к фх иди нахуй
> 
> матиеу так сказал

матиеу=чс😼😼😼😼😼😼😼

**Comment by cafeed28** [comment]
![unknown-88.png](https://user-images.githubusercontent.com/62172116/162610781-50941d67-762d-4497-9040-f2d55ae28b16.png)

все равно тут в дс эмбеды не грузятся

**Comment by cafeed28** [comment]
Умер атеист — попал в Aд. Огляделся — океан, песчаный пляж, пальмы, солнышко светит. Навстречу ему Сатана.  — Добро пожаловать, там в баре напитки, отдыхай.  — А потом?  — Будет скучно - сходи на дискотеку, познакомишься с кем... Тут много развлечений всяких!  Идет атеист вдоль берега, потягивает кампари, наслаждается загробной жизнью... Вдруг, среди высоких скал - темная пещера, вонючий дым и языки пламени. Ужасные черти варят людей в котлах со смолой, жарят на огромных сковородах и вообще всячески измываются над беднягами, которые издают душераздирающие вопли.  Прошибло потом атеиста, бегом к Сатане, язык со страху заплетается, в чем дело, спрашивает.  — А! Это, брат, верующие. Они так захотели.

**Comment by FlameFLPS** [comment]
авчемприкол

**Comment by DiegoArmando-27** [comment]
л

**Comment by RUCItLrHy3Ub** [comment]
<@!863533778302795797>

**Comment by DiegoArmando-27** [comment]
😅😂🤣

**Comment by DiegoArmando-27** [comment]
ps!c

**Comment by FlameFLPS** [comment]
пацаны привет чо как дела

**Comment by FlameFLPS** [comment]
последнее сообщение неделю назад ровно

**Comment by FlameFLPS** [comment]
хы

**Comment by FlameFLPS** [comment]
.-.

**Comment by FlameFLPS** [comment]
кафіфы против карасей

**Comment by FlameFLPS** [comment]
хз

**Comment by FlameFLPS** [comment]
тут никого не

**Comment by FlameFLPS** [comment]
т

**Comment by FlameFLPS** [comment]
скучна

**Comment by FlameFLPS** [comment]
:smiling_imp:

**Comment by FlameFLPS** [comment]
<@#863435774351245317>

**Comment by FlameFLPS** [comment]
не то

**Comment by FlameFLPS** [comment]
<@&863435774351245317>

**Comment by FlameFLPS** [comment]
во

**Comment by FlameFLPS** [comment]
караси крч просыпайтесь

**Comment by FlameFLPS** [comment]
а я пошёл

**Comment by FlameFLPS** [comment]
(ес че я знаю что не пингует никого)

**Comment by FlameFLPS** [comment]
если кто это увидит поставьте лайк :+1:

**Comment by DiegoArmando-27** [comment]
<:cosmiccyc:970226910640619540>

**Comment by YaStawex** [comment]
Космик дно

**Comment by linwys** [comment]
ps!c

**Comment by YaStawex** [comment]
сви дно

**Comment by linwys** [comment]
Фууу

**Comment by DiegoArmando-27** [comment]
согл

**Comment by YaStawex** [comment]
Сакупен серклз старЫй гуд

**Comment by YaStawex** [comment]
ребят кто первый напишет в чат тот бог король

**Comment by YaStawex** [comment]
А кто второй лiх

**Comment by YaStawex** [comment]
Чат на руфхбалбесы

**Comment by linwys** [comment]
Согл

**Comment by YaStawex** [comment]
да ты балбес алюм

**Comment by YaStawex** [comment]
я написал что на руфх чат надо

**Comment by YaStawex** [comment]
А не сюда

**Comment by YaStawex** [comment]
Так что сам ты согл

**Comment by YaStawex** [comment]
🇸🇴🇸🇻🇨🇿🇷🇴🇲🇪🇲🇰🇲🇪🇲🇰🇨🇿

**Comment by linwys** [comment]
Иди нахуй я в бане сразу буду 😭

**Comment by DiegoArmando-27** [comment]
[](url)

**Comment by YaStawex** [comment]
Ещё твинк создашь

**Comment by linwys** [comment]
Мне лень

**Comment by YaStawex** [comment]
фу ленивый

**Comment by YaStawex** [comment]
зуйло

**Comment by YaStawex** [comment]
ОЙЙЙ

**Comment by YaStawex** [comment]
ps!c

**Comment by linwys** [comment]
[eTGGDVwj_kY-1](https://user-images.githubusercontent.com/91447283/166137005-e8e63e27-beb2-475f-91a5-c9b26bc72e4e.jpg)

**Comment by DiegoArmando-27** [comment]
на фотке алюм

**Comment by DiegoArmando-27** [comment]
ОЙ

**Comment by linwys** [comment]
Ура я трахал осла

**Comment by YaStawex** [comment]
![](https://media.discordapp.net/attachments/937238747949465600/970229757134397470/IMG_9145.png)

**Comment by cafeed28** [comment]
поч всё ещё никто не написал нворд

**Comment by YaStawex** [comment]
:flag_ne: :flag_gr:

**Comment by YaStawex** [comment]
блять)

**Comment by cafeed28** [comment]
так неинтересно

**Comment by YaStawex** [comment]
бан на руфх будет или нет

**Comment by cafeed28** [comment]
ёбаный гитхаб хватит слать мне эту хйню на почту

**Comment by YaStawex** [comment]
Хотя нет скорее

**Comment by YaStawex** [comment]
Потому что это гитхаб)

**Comment by linwys** [comment]
![eTGGDVwj_kY-1](https://user-images.githubusercontent.com/91447283/166137140-cd35ffa2-e01b-4787-bc0d-0bd3a544f769.jpg)

**Comment by linwys** [comment]
О

**Comment by cafeed28** [comment]
АХАХАХАХАХА

**Comment by linwys** [comment]
Имба

**Comment by cafeed28** [comment]
![image](https://user-images.githubusercontent.com/62172116/166137150-25c62aec-5261-444d-9f70-9075b2150b79.png)
хуйня

**Comment by YaStawex** [comment]
Алюм не

**Comment by linwys** [comment]
Да

**Comment by linwys** [comment]
Бля

**Comment by linwys** [comment]
Гитхаб чмо:(

**Comment by linwys** [comment]
![image0-141](https://user-images.githubusercontent.com/91447283/166137182-79666a8d-74f4-4c06-a1e5-de68e734354a.gif)

**Comment by DiegoArmando-27** [comment]
🪘

**Comment by linwys** [comment]
Кафиюф

**Comment by linwys** [comment]
Кафиф

**Comment by linwys** [comment]
Ты гий

**Comment by dark11mm** [comment]
негры пидорасы

**Comment by DiegoArmando-27** [comment]
кто удалил нворд

**Comment by DiegoArmando-27** [comment]
по фактц же было

**Comment by DiegoArmando-27** [comment]
ойЧЕ

**Comment by GDenisC** [comment]
АХАХХАХАХАХА НВОРД НА ФХ В #github СВЕРХУ

**Comment by YaStawex** [comment]
БЛЯЯЯТЬ гитхаб хуйло ебаное

**Comment by YaStawex** [comment]
Да дискорд даже не лучше

**Comment by YaStawex** [comment]
я просто удалил дс и теперь мне везде просит зайти в аккаунт дс что бы продолжить

**Comment by YaStawex** [comment]
гитхаб исключение

**Comment by YaStawex** [comment]
Здесь просто из акка вышло

**Comment by GDenisC** [comment]
зач дс удалил

**Comment by YaStawex** [comment]
Да я далбаеб просто

**Comment by YaStawex** [comment]
Случайно

**Comment by GDenisC** [comment]
когда гиткорд

**Comment by YaStawex** [comment]
@Partur-dev Када галясиум , хуз и гиткорд

**Comment by YaStawex** [comment]
Ждем

**Comment by GDenisC** [comment]
хуз щавтра, галаксиум вчера а гиткорд после галаксиума

**Comment by DiegoArmando-27** [comment]
я сноубордер

**Comment by DiegoArmando-27** [comment]
🏂

**Comment by YaStawex** [comment]
А я 🧗🏿Скололаз конченый

**Comment by YaStawex** [comment]
Если на этом сообщение на руфх в канале #github наберется 10 сноубордистов 🏂 дейроз спляшет лезгинку на камеру !!!!!!!!

**Comment by YaStawex** [comment]
Дейроз прости но если ты не выполнишь это то я к тебе лично домой приеду с 7-ю мускулистыми нвордами и выебу тебя

**Comment by YaStawex** [comment]
Ура звезды

**Comment by YaStawex** [comment]
Мы набрали 10 сноубордистов!! Теперь дейроз будет обязан сплясать лезгинку на камеру. Если он не спляшет он должен будет поставить себе юзернем в дискорде «ясосалхуй» окда

**Comment by KREZYT** [comment]
Я хуесос и я признаю

**Comment by DiegoArmando-27** [comment]
пон

**Comment by GDenisC** [comment]
дед чат

**Comment by DiegoArmando-27** [comment]
аэ\

**Comment by GDenisC** [comment]
здравствйте

**Comment by 15baller** [comment]
Я засыпаю без спокойной ночи
я просыпаюсь без доброе утро
я могу жить без я горжусь тобой
потому-что в конечном итоге всё что у меня есть
это
я сам
![IMG_20230202_080117_125](https://user-images.githubusercontent.com/118118572/216766003-e00b8336-c40b-46b2-8844-40b7819f51a6.jpg)

**Comment by linwys** [comment]
Пон
